Numpy

Numpy - init

In [56]:
import numpy as np

Numpy - 1D array

In [57]:
array_1d = np.array([1,2,3,4])

array_1d

array([1, 2, 3, 4])

In [58]:
array_1d.shape

(4,)

In [59]:
array_2d = np.array([[1,2,3,4,5], [6,7,8,9,10]])

array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
array_2d.shape

(2, 5)

SLICING

In [61]:
array_1d

array([1, 2, 3, 4])

In [62]:
array_1d[2:]

array([3, 4])

In [63]:
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [64]:
array_2d[1:,2:]

array([[ 8,  9, 10]])

In [65]:
array_sample_1 = np.array([1,2,3,4,5,6,7,8,9,10])

MANIPULATION

In [66]:
np.reshape(array_sample_1,(2,5))


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

We cannot reshape an array of 10 elements into 3X3 as 1 ele is left out

In [67]:
np.reshape(array_sample_1,(3,3))

ValueError: cannot reshape array of size 10 into shape (3,3)

In [ ]:
sample_array_1 = np.reshape(array_sample_1,(5,2))

sample_array_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.ndarray.flatten(sample_array_1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
test_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
test_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
test_array.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Additional Array Creation Functions

In [ ]:
np.full((5,5), 9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [ ]:
np.arange(0, 10) # Creates an array of values from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0, 10, 5) # Creates an array of 5 values evenly spaced between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.random.rand(3,3) # Creates a 3x3 array of random values between 0 and 1

array([[0.25765013, 0.0340396 , 0.66570951],
       [0.92397373, 0.96478184, 0.9315756 ],
       [0.83944427, 0.72413707, 0.29541554]])

In [ ]:
np.random.randint(1,100, (5,5)) # Creates a 5x5 array of random integers between 1 and 100

array([[81, 41, 17, 24, 15],
       [59, 41, 16, 10, 44],
       [54, 11, 68, 89, 21],
       [14, 83, 82, 37, 59],
       [76, 48, 30, 94, 25]], dtype=int32)

In [ ]:
x = np.random.randint(1,100, (5,5))
x

array([[48, 62, 75, 46,  8],
       [73, 91, 40, 85, 99],
       [19, 45,  5, 81, 56],
       [39,  3,  3, 34, 87],
       [10, 81,  7, 93, 29]], dtype=int32)

In [ ]:
np.sum(x)                     # Sum of all elements in the array

np.int64(1219)

In [ ]:
array_1 = np.random.randint(1,50,(3,3))
array_1

array([[24, 22, 21],
       [41,  8, 12],
       [47, 32, 30]], dtype=int32)

In [ ]:
array_2 = np.random.randint(1,89,(3,3))
array_2

array([[88, 27, 83],
       [79, 88, 21],
       [69, 22, 39]], dtype=int32)

In [55]:
array_1 + array_2


array([[112,  49, 104],
       [120,  96,  33],
       [116,  54,  69]], dtype=int32)

In [69]:
y = np.random.randint(1,100, (4,4))
y

array([[11, 24, 77, 30],
       [72, 30, 20,  1],
       [88, 80, 97, 61],
       [23, 10, 72, 55]], dtype=int32)

In [70]:
y.mean()

np.float64(46.9375)

In [75]:
np.mean(y)

np.float64(46.9375)

In [72]:
np.mean(y, axis=0)  # Mean of each column

array([48.5 , 36.  , 66.5 , 36.75])

In [74]:
np.mean(y, axis=1)

array([35.5 , 30.75, 81.5 , 40.  ])

In [76]:
np.amax(y)

np.int32(97)

In [77]:
np.amax(y, axis=0)  # Max of each column

array([88, 80, 97, 61], dtype=int32)

In [78]:
np.amax(y, axis=1)  # Max of each row

array([77, 72, 97, 72], dtype=int32)

np.loadtxt()
np.genfromtxt()

In [87]:
z = np.genfromtxt('tfl-daily-cycle-hires.txt', delimiter=',', usecols=(0,1), skip_header=1, dtype=[str, float])

In [92]:
z

array([('',  6897.), ('',  5564.), ('',  4303.), ..., ('', 32539.),
       ('', 39889.), ('', 34070.)],
      shape=(4081,), dtype=[('f0', '<U'), ('f1', '<f8')])

In [93]:
z.shape

(4081,)

In [101]:
# Using loadtxt with dtype=object for mixed types
z_2d_direct = np.loadtxt('tfl-daily-cycle-hires.txt', delimiter=',', usecols=(0,1), skiprows=1, dtype=object)
z_2d_direct[:, 1] = z_2d_direct[:, 1].astype(float)

z_2d_direct

array([['30/07/2010', 6897.0],
       ['31/07/2010', 5564.0],
       ['01/08/2010', 4303.0],
       ...,
       ['28/09/2021', 32539.0],
       ['29/09/2021', 39889.0],
       ['30/09/2021', 34070.0]], shape=(4081, 2), dtype=object)

In [102]:
z_2d_direct.shape


(4081, 2)

In [103]:
zz = z_2d_direct[:,1]

In [104]:
zz

array([6897.0, 5564.0, 4303.0, ..., 32539.0, 39889.0, 34070.0],
      shape=(4081,), dtype=object)

In [105]:
zz.mean()

np.float64(26261.932124479295)

In [106]:
zz.min()

2764.0

In [107]:
zz.max()

73094.0

In [108]:
zz.std()

np.float64(9740.107235227799)